### ISSUE TITLE
error: unable to load valid module manifest

### ISSUE THREAD

**Issue by ceccozin** [krbz999/foundryvtt-items-with-spells-5e#11]
error when trying to install the module in foundry (sorry for bad english)

screenshot error foundry:
![image](https://github.com/krbz999/foundryvtt-items-with-spells-5e/assets/38471189/255dcec3-ec56-4d6f-bced-76696a3633eb)

screenshot manifest page (in foundry site):
![image](https://github.com/krbz999/foundryvtt-items-with-spells-5e/assets/38471189/1444c060-c1d3-4a67-b562-64948079a73c)

if i take manifest link from repository i can install:
![image](https://github.com/krbz999/foundryvtt-items-with-spells-5e/assets/38471189/c1d542d8-8f74-402c-80b5-aacb1db903b5)

**Comment by krbz999** [comment]
Thanks, this was an error on the foundry admin page. Updating worked fine, but installing did not. It should be fixed now.
