### ISSUE TITLE
Feature Request - Add Features to Items

### ISSUE THREAD

**Issue by KonteiKeisei** [krbz999/foundryvtt-items-with-spells-5e#15]
A similar module to this called Magic Items 2 apparently allows for the adding of non spells such as features to items as well.
Is that something that could be implemented without to much trouble?

I ask because this module continues to receive support.

Either way, Thank you for keeping up with this Module, it is Fantastic.

**Comment by Dyrnwyrm** [comment]
I second this request, Items with spells is a nice module and adding features will probably enhance it more, i hope this isnt a request beyond the scope of the module

**Comment by krbz999** [comment]
See my comment here: https://github.com/foundryvtt/dnd5e/pull/2630#issuecomment-1819075440
