### ISSUE TITLE
Issue with Item Sheet renderLite() function

### ISSUE THREAD

**Issue by kgar** [krbz999/foundryvtt-items-with-spells-5e#16]
In `scripts\classes\item-sheet.js`, `renderLite()` function, the check for `tabs` is referring to a jquery result set, so `if (!tabs) return;` will never return early, even if there are 0 results from the `.find()`.

Can it be changed to `if (!tabs.length) return;` or a functional equivalent?

**Comment by krbz999** [comment]
Ew, jQuery. Gross.

**Comment by kgar** [comment]
Thank you! And the vanilla JS 💘
