### ISSUE TITLE
Only show spells if item is equipped and recharge override

### ISSUE THREAD

**Issue by pefcs** [krbz999/foundryvtt-items-with-spells-5e#17]
1)
Would it be possible to add an option that the spell is only shown in the spell list if the item is equipped?
I know you can do a workaround with Atunement, but it would be great to create items which doesn't need atunement, but the players could only use the attached spell(s), if they equipped the item.

2)
Another override option would also be great for the spells. Now you can override the charge amount, but not the recharge formula. Sure, you can manually change it, or create a variant spell with eg. 1/1 charges and recharge formula, use this variant and override the charges, but it would be better if you wouldn't need to do this, just drag and drop the spell, add the charges and specify the formula override. Would this be possible?

**Comment by morepurplemorebetter** [comment]
I have implemented the 1st point of this request. In v11.2.0 there is a setting to hide spells from unequipped items.

You can find this module on [my GitHub from now on](https://github.com/morepurplemorebetter/fvtt-items-with-spells-5e) as I've taken it over from Zhell.

If you are still interested in the 2nd point of your request, please make a [feature request in the new repo](https://github.com/morepurplemorebetter/fvtt-items-with-spells-5e/issues) and I'll see when I can implement it.
