### ISSUE TITLE
Configure Override window doesn't appear

### ISSUE THREAD

**Issue by asherett** [krbz999/foundryvtt-items-with-spells-5e#19]
When I click the Edit button on a spell added to an item, the Configure Override window shown in the module presentation doesn't appear. Instead I get the normal spell sheet.

Tested in a completely blank new world with no modules running except Items With Spells 5e and Libwrapper:

![image](https://github.com/krbz999/foundryvtt-items-with-spells-5e/assets/76103282/5c653def-32f9-4165-874b-f5f8caefd9bd)

No errors are generated in console or otherwise.

FVTT 11.315, Items with Spells DnD5e 11.1.1, DnD5e 2.4.1, libWrapper 1.12.13.0
Browser: Chrome Version 120.0.6167.140 (Official Build) (64-bit)

**Comment by krbz999** [comment]
Hello, is this an owned item? If so, please see #5 and #14

**Comment by asherett** [comment]
Ooooh. That would explain it. Completely my bad, I did read "Only works for Unowned Items", but I didn't fully grasp the meaning of "unowned". Resolved.

**Comment by krbz999** [comment]
This comes up a lot, and it should be more intuitive than it is. :-)
