### ISSUE TITLE
Cannot drag spells to the IWS tab of an item when the item is located on an actor

### ISSUE THREAD

**Issue by dale-e-o** [krbz999/foundryvtt-items-with-spells-5e#2]
In v11 I cannot draga spells from item or compendiums to the spells tab.

Version 11.304
DND world 2.2.1

**Comment by MythicalRollers** [comment]
Can also confirm this.  Unable to add spells to an item/feature on a character sheet since 11.304.  I can as a DM add the spells if its just in the items tab.

**Comment by krbz999** [comment]
I am not certain this has ever been an intended use.

**Comment by MythicalRollers** [comment]
Foundry: 10.303
dnd5e: 2.2.1
IwS: 1.3.1
You can do so in the above version.  And it is the best thing ever.  It's how I organize what feature or item gives my players additional spells, without having to clutter my items tab.  I love this feature.  I hope you can bring it back in V11.X dnd5e 2.2.X

**Comment by MythicalRollers** [comment]
No warnings, or errors in the console to help diagnose.
