### ISSUE TITLE
DnD 5e Version 3.0.1 Update

### ISSUE THREAD

**Issue by DuncanDT20** [krbz999/foundryvtt-items-with-spells-5e#22]
I see you currently have no intentions of making an update in your issues tab. I would be willing to give a donation to see this module back working again as I got a lot of mileage out of it.

**Comment by krbz999** [comment]
While that's certainly an appreciated sentiment, a github issue is not the place to discuss or propose such a thing. \:)

**Comment by DuncanDT20** [comment]
That is very fair, my apologies
