### ISSUE TITLE
[Feature Request] Compatibility with DND5E Version 3.0

### ISSUE THREAD

**Issue by SirAron111** [krbz999/foundryvtt-items-with-spells-5e#24]
The module worked well with the previous version, and all my players have items with spells on them. But in DnD5E 3.0 it doesn't let me enable the module because the version is too low.
Is it possible to update it? Or do I have to revert to early version?

**Comment by krbz999** [comment]
There are currently no plans to update `Items With Spells` for version 3 of the dnd5e system.

Please also see issues #20 through #23.

**Comment by SirAron111** [comment]
?? But why does 3.0 add spells to items?
