### ISSUE TITLE
[BUG] The attack bonus of spells are somtimes set to `null`, preventing attack rolls from being performed

### ISSUE THREAD

**Issue by KikinChikin** [krbz999/foundryvtt-items-with-spells-5e#25]
Any time i set a spell that requires an attack roll to use charges from the parent item i cannot make the attack roll. I have tried disabling all other modules and tried multiple spells from SRD and custom made. Ive also tried multiple version of the module and of the dnd5e system.

**Comment by krbz999** [comment]
I struggle to believe this can be caused by this module, it doesn't touch that area of the system at all. Also, no repro steps provided.

**Comment by KikinChikin** [comment]
> I struggle to believe this can be caused by this module, it doesn't touch that area of the system at all. Also, no repro steps provided.

Sorry about that, forgot about that part. Make a parent item and give it any number of charges. Add a spell that requires an attack roll. Make the spell consume charges off the parent item. Add the item to a character sheet. Roll the spell from the spell book, then roll the attack roll from the prompt in the chat box. Nothing happens.

**Comment by krbz999** [comment]
What's the error in the console?

**Comment by KikinChikin** [comment]
![error](https://github.com/krbz999/foundryvtt-items-with-spells-5e/assets/83473647/81d81393-8af6-4ef3-879e-8ccb75241a1c)

**Comment by krbz999** [comment]
Your spell is not set up correctly, it's getting an attack roll bonus of "null" from somewhere.

**Comment by KikinChikin** [comment]
The spell works just fine when its consuming a spell slot instead, all i am doing is making consume item charges and it suddenly does this.

**Comment by krbz999** [comment]
export the spell.

**Comment by KikinChikin** [comment]
Its jsut the SRD firebolt ive been testing with there. I have used other spells though. Only thing ive done to it is drag and drop into the "spells" section of the parent item.
[fvtt-Item-fire-bolt-cFCkbFqOVzG4sEIB.json](https://github.com/krbz999/foundryvtt-items-with-spells-5e/files/14383565/fvtt-Item-fire-bolt-cFCkbFqOVzG4sEIB.json)

**Comment by krbz999** [comment]
OK I see the issue.
