### ISSUE TITLE
Any chance this could work with DnD5e 3.1.1?

### ISSUE THREAD

**Issue by mrmattwilkins** [krbz999/foundryvtt-items-with-spells-5e#28]
I think the latest this module will work with is 2.4.9.  Any chance this will be upgraded?  Or the functionality rolled into DnD5e?  Or maybe there is another way around the problem of having an item, such as the Staff of the Magi with a zillion spells on it, but not being able to automatically do the hit and damage rolls?
Cheers
Matt

**Comment by krbz999** [comment]
There aren't currently any plans for me to update this module to work with dnd5e v3.

**Comment by mrmattwilkins** [comment]
Thanks Zhell, I have found magic items 2 which seems to do what I want, thank you!
