### ISSUE TITLE
[Bug] Display of Spell Icons is messed up and creat Spells Button appears in spell list but doesn't work

### ISSUE THREAD

**Issue by SirAron111** [krbz999/foundryvtt-items-with-spells-5e#3]
So I switched over to this module from the magic items' module. It works fine, but I noticed a few issues.

So for one, the Icons don't use the right proportions in the Edit tab for the spells of the Item. Causing them to be snipped and partially zoomed in like hell. This also causes the format to get broken.
![Unbenannt](https://github.com/krbz999/foundryvtt-items-with-spells-5e/assets/39855956/996ca7f6-0e76-4246-9d1a-18b11ea2de73)
It's also annoying that you can't add or edit the new spells onto the item while it's on a player. You always have to copy it back to the items tab and edit it there, and then give it back to the player.

Another thing is that this strange create spell button appears on the char sheets spellbook along the spells. Even for the players. It confuses the players and when they click it by accident it throws an error message, so it doesn't even do anything. (could that be removed or at least hidden from the player's side?)
![Unbenannt2](https://github.com/krbz999/foundryvtt-items-with-spells-5e/assets/39855956/474e3a26-3492-4072-9bc0-857f798df2b6)

And finally, is there no config option to set the spell tab in the item edit window to be invisible for players?

**Comment by krbz999** [comment]
I suggest consulting your UI modules. Non-repro.

![image](https://github.com/krbz999/foundryvtt-items-with-spells-5e/assets/50169243/959354ba-ae7c-4574-9420-b71e6b16d31f)
![image](https://github.com/krbz999/foundryvtt-items-with-spells-5e/assets/50169243/48bca5c2-a673-4b7c-bed1-3104c62aa488)
