### ISSUE TITLE
Edit button opens the basic item configuration v11.0.2

### ISSUE THREAD

**Issue by OzBezerius** [krbz999/foundryvtt-items-with-spells-5e#5]
When the edit button is clicked it opens the basic item config instead of the override menu to set up the item changes
![image](https://github.com/krbz999/foundryvtt-items-with-spells-5e/assets/25015102/45f457cd-4d32-424b-b11f-34af95f94cf2)

**Comment by krbz999** [comment]
This is working as intended when the item is already owned by an actor. If you want to change the magic item's setup of its spells, create it in the items directory instead of on an actor.
