### ISSUE TITLE
Module missing from Module management

### ISSUE THREAD

**Issue by Weskernation** [krbz999/foundryvtt-items-with-spells-5e#9]
The module is installed using the json file. and I can see it on the "Add-on Modules" list.
when starting a world, the module is not available in "Manage Modules" list

Running V10.312
System 5e v**2.3.1**

FIXED Manually

After installation, in the /data/modules/items-with-spells-5e/module.json 

look for the following and change:

    ],
    "relationships": {
        "systems": [
            {
                "id": "dnd5e",
                "type": "system",
                "compatibility": {
                    "minimum": "2.2.1",
                    "maximum": "2.2.9"**   ->  **"2.3.9"
                }
            }
        ],

Now the module is visible and activatable again

**Comment by krbz999** [comment]
You are on v10. The newest updates support v11.
